### ISSUE TITLE
Switch to Floskell

### ISSUE THREAD

**Issue by just95** [FreeProving/guidelines#5]
## Description

We want to use [Floskell](https://hackage.haskell.org/package/floskell) instead of Brittany for formatting.

## Motivation

Currently we are using [Brittany](https://hackage.haskell.org/package/brittany) for formatting Haskell source code.
Brittany is one of the few Haskell formatters that breaks up long lines and whose output is independent of the formatting chosen by the user. Unfortunately, Brittany supports only very few language constructs (mainly function declarations). Data type declarations are not formatted and imports are not sorted. Furthermore there is a bug on Windows that causes carriage return characters in comments to be duplicated. Thus, we've looked for a different formatter.

Of those formatters we've tested, [Floskell](https://hackage.haskell.org/package/floskell) was the only formatter that produced satisfying results. Like Brittany, Floskell breaks up long lines. Since Floskell takes operator precedence into account, it acually breaks up lines better than Brittany. Additionally, Floskell formats data type declarations, sorts imports and has many configuration options.

## Tasks

The following tasks should be done in the `guidelines` repository.

 - [x] Add a template configuration file for Floskell that matches our coding style.
 - [x] Replace sections about Brittany in the `CONTRIBUTING.md` file by sections about Floskell.
 - [x] Update the Haskell Styleguide in `CONTRIBUTING.md`. Aspects covered by Floskell don't have to be mentioned anymore.
 - [x] Mention the exact Floskell version used by the CI pipeline in `CONTRIBUTING.md`.

Open an issue or pull request on all other repositories with the following tasks.

 - [x] Add a Floskell confiuguration file based on the template in the [`guidelines`](https://github.com/FreeProving/guidelines) repository. Adapt the configuration file based on the repository's needs (e.g., language extensions and prefixes for grouping of imports). Do not change formatting options. Code style should be consistent across all repositories. 
 - [x] Update the `./tool/check-formatting.sh` and `./tool/format-code.sh` (and in case of the Free Compiler `./tool/full-test.sh`) scripts to use Floskell. Preferably copy an updated version from another repository.
 - [x] Update the configuration of the CI pipeline. Preferably copy updated CI jobs from another repository.
 - [x] Format code using Floskell.
 - [x] Check the code for errors or odd formatting introduced by Floskell. Adapt the configuration file if necessary.

Additionally, we will have to publish a Docker image for the CI pipeline that has the right version of Floskell preinstalled. For Brittany, I've created [`just95/brittany`](https://hub.docker.com/r/just95/brittany). The Dockerfile for Floskell should require only very little changes.
